const copy = {
  es: {
    title: "Perfil de viajero",
    addPhoto: "Agregar foto",
    personalInfo: "Informacion personal",
    savedOk: "Perfil guardado correctamente",
    loading: "Cargando...",
    name: "Nombre",
    namePh: "Tu nombre",
    lastName: "Apellido",
    lastNamePh: "Tu apellido",
    country: "Pais de residencia",
    countryPh: "Tu pais de residencia",
    city: "Ciudad",
    cityPh: "Tu ciudad",
    language: "Idioma principal",
    languagePh: "Tu idioma principal",
    phone: "Telefono",
    phonePh: "Tu numero de contacto",
    travelStyle: "Tipo de viaje",
    travelStylePh: "Relax, aventura, cultura, familia",
    interests: "Intereses",
    interestsPh: "Historia, gastronomia, naturaleza, arte",
    about: "Sobre vos",
    aboutPh: "Conta brevemente que experiencia te gustaria vivir",
    saving: "Guardando...",
    saved: "Perfil guardado",
    save: "Guardar",
    logout: "Cerrar sesion",
    updated: "Perfil actualizado",
    saveError: "No se pudo guardar"
  },
  en: {
    title: "Traveler profile",
    addPhoto: "Add photo",
    personalInfo: "Personal information",
    savedOk: "Profile saved successfully",
    loading: "Loading...",
    name: "First name",
    namePh: "Your first name",
    lastName: "Last name",
    lastNamePh: "Your last name",
    country: "Country of residence",
    countryPh: "Your country of residence",
    city: "City",
    cityPh: "Your city",
    language: "Main language",
    languagePh: "Your main language",
    phone: "Phone",
    phonePh: "Your contact number",
    travelStyle: "Travel style",
    travelStylePh: "Relax, adventure, culture, family",
    interests: "Interests",
    interestsPh: "History, food, nature, art",
    about: "About you",
    aboutPh: "Briefly describe the experience you would like to have",
    saving: "Saving...",
    saved: "Profile saved",
    save: "Save",
    logout: "Log out",
    updated: "Profile updated",
    saveError: "Could not save"
  }
};